name: Code Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision flake8


    - name: Run code checks
      run: |
        python .github/scripts/check_model.py
